# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(parsnip)
    library(ranger)
    library(workflows)
}
b <- board_rsconnect("envvar", server = "https://colorado.posit.co/rsc")
v <- vetiver_pin_read(b, "katie.masiello/katie_sacramento_rf", version = "56410")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
